/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.LoginDAO;
import Javabeans.Login;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import DAO.ValidadorCPF;

/**
 *
 * @author Tiago Fochesatto
 */
public class TelaOpc extends javax.swing.JFrame {

    /**
     * Creates new form frameOpc
     */
    public TelaOpc() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbpasswmnm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtuser = new javax.swing.JTextField();
        lbuser = new javax.swing.JLabel();
        lbsenha = new javax.swing.JLabel();
        lbpasswmnm = new javax.swing.JLabel();
        psswsenha = new javax.swing.JPasswordField();
        lbcnfsenha = new javax.swing.JLabel();
        psswconfsenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        lbnasc = new javax.swing.JLabel();
        lbcpf = new javax.swing.JLabel();
        lbsexo = new javax.swing.JLabel();
        fmtxtcpf = new javax.swing.JFormattedTextField();
        cbsexo = new javax.swing.JComboBox();
        fmtxtnasc = new javax.swing.JFormattedTextField();
        txtemail = new javax.swing.JTextField();
        lbemail = new javax.swing.JLabel();
        lbfone = new javax.swing.JLabel();
        fmtxtfone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        btnCriar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(19, 38, 44));
        jPanel5.setForeground(new java.awt.Color(19, 38, 44));

        jPanel3.setBackground(new java.awt.Color(54, 63, 73));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Criar login");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-backspace-50.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );

        jPanel4.setBackground(new java.awt.Color(34, 41, 50));

        txtuser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });

        lbuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbuser.setForeground(new java.awt.Color(255, 255, 255));
        lbuser.setText("Usuário:");

        lbsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbsenha.setForeground(new java.awt.Color(255, 255, 255));
        lbsenha.setText("Senha:");

        lbpasswmnm.setForeground(new java.awt.Color(204, 0, 0));
        lbpasswmnm.setText("No mínimo 4 caracteres");

        psswsenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        psswsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psswsenhaKeyPressed(evt);
            }
        });

        lbcnfsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbcnfsenha.setForeground(new java.awt.Color(255, 255, 255));
        lbcnfsenha.setText("Confirmar senha:");

        psswconfsenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        psswconfsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswconfsenhaActionPerformed(evt);
            }
        });
        psswconfsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psswconfsenhaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dados de login");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbcnfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbuser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psswsenha)
                    .addComponent(txtuser)
                    .addComponent(psswconfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbpasswmnm)))
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lbuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsenha)
                    .addComponent(lbpasswmnm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psswsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbcnfsenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psswconfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(34, 41, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informações pessoais e de contato:");

        lbnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbnome.setForeground(new java.awt.Color(255, 255, 255));
        lbnome.setText("Nome completo:");

        txtnome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        lbnasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbnasc.setForeground(new java.awt.Color(255, 255, 255));
        lbnasc.setText("Nascimento:");

        lbcpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbcpf.setForeground(new java.awt.Color(255, 255, 255));
        lbcpf.setText("Cpf:");

        lbsexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbsexo.setForeground(new java.awt.Color(255, 255, 255));
        lbsexo.setText("Sexo:");

        try {
            fmtxtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         ", "Masculino", "Feminino", "Outro" }));
        cbsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsexoActionPerformed(evt);
            }
        });

        try {
            fmtxtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtemail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });

        lbemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbemail.setForeground(new java.awt.Color(255, 255, 255));
        lbemail.setText("Email:");

        lbfone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbfone.setForeground(new java.awt.Color(255, 255, 255));
        lbfone.setText("Telefone:");

        try {
            fmtxtfone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtfone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmtxtfoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fmtxtfone)
                            .addComponent(fmtxtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbfone, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fmtxtnasc)
                            .addComponent(cbsexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbnasc)
                                    .addComponent(lbsexo))
                                .addGap(0, 56, Short.MAX_VALUE))))
                    .addComponent(lbnome)
                    .addComponent(lbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail)
                    .addComponent(txtnome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbemail)
                .addGap(1, 1, 1)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcpf)
                    .addComponent(lbsexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmtxtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfone)
                    .addComponent(lbnasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmtxtfone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fmtxtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        jPanel2.setBackground(new java.awt.Color(34, 41, 50));

        btnCriar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCriar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    private void psswconfsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswconfsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswconfsenhaActionPerformed
    
    //Variáveis Auxiliares
    int erro,dterro,vzerro, d, m, a;
    String dia, mes, ano, strgSexo= "indefinido";
    
    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
       
        // Botão Criar:
        try{
            
            LoginDAO dao = new LoginDAO();
            erro=0;
            dterro=0;
            vzerro=0;
            //Verifica se há algum campo em branco:
            //Usuário:
            if(txtuser.getText().isEmpty() || txtuser.getText().length()>30){
                lbuser.setText("Usuário*:");
                lbuser.setForeground(java.awt.Color.red);
                
                vzerro = 1;
            }
            else{
                lbuser.setText("Usuário:");
                lbuser.setForeground(java.awt.Color.white);
            }
            
            //senha:
            if(psswsenha.getText().isEmpty() || psswsenha.getText().length()>20){
                lbsenha.setText("Senha*:");
                lbsenha.setForeground(java.awt.Color.red);
                lbcnfsenha.setText("Confirmar senha*:");
                lbcnfsenha.setForeground(java.awt.Color.red);
                
                vzerro = 1;
            }
            else{
                lbsenha.setText("Senha:");
                lbsenha.setForeground(java.awt.Color.white);
                lbcnfsenha.setText("Confirmar senha:");
                lbcnfsenha.setForeground(java.awt.Color.white);
            }
            if(psswsenha.getText().length()<4){
                lbpasswmnm.setVisible(true);
                lbsenha.setText("Senha*:");
                lbsenha.setForeground(java.awt.Color.red);
            }
            else{
                lbpasswmnm.setVisible(false);
            }
            
            //nome:
            if(txtnome.getText().isEmpty() || txtnome.getText().length()>50){
                lbnome.setText("Nome Completo*:");
                lbnome.setForeground(java.awt.Color.red);
                
                vzerro = 1;
            }
            else{
                lbnome.setText("Nome Completo:");
                lbnome.setForeground(java.awt.Color.white);
            }
            if(strgSexo.equals("indefinido")){
                lbsexo.setText("Sexo*:");
                lbsexo.setForeground(java.awt.Color.red);
                vzerro = 1;
            }
            else{
                lbsexo.setText("Sexo:");
                lbsexo.setForeground(java.awt.Color.white);
            }
            
            //Verifica se o formato do email é válido:
            if (!(Pattern.matches("^[a-zA-Z0-9.]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", 
                    txtemail.getText())) & erro==0 || txtemail.getText().isEmpty() 
                    || txtemail.getText().length()>60) {               
                lbemail.setText("Email*:");
                lbemail.setForeground(java.awt.Color.red); 
                erro = 1;
                txtemail.setText(null);
            }
            else{
                lbemail.setText("Email:");
                lbemail.setForeground(java.awt.Color.white);
            }
            
            //confirma a senha:
            if(psswsenha.getText().equals(psswconfsenha.getText())){                
            }
            else {
                lbsenha.setText("Senha*:");
                lbsenha.setForeground(java.awt.Color.red);
                lbcnfsenha.setText("Confirmar senha*:");
                lbcnfsenha.setForeground(java.awt.Color.red);
                
                JOptionPane.showMessageDialog(null, "Erro ao confirmar senha!", "Incompatible passwords!",
                        JOptionPane.ERROR_MESSAGE);
                erro = 1;
            }
            
            //Verifica se o usuário já consta no bd:
            if(dao.RepeticaoUser(txtuser.getText())){
                lbuser.setText("Usuário*:");
                lbuser.setForeground(java.awt.Color.red);
                JOptionPane.showMessageDialog(null, "Este usuário já está cadastrado no banco de dados!", "Invalid user name!", JOptionPane.ERROR_MESSAGE);
                erro = 1;
                txtuser.setText(null);
            }
            
            //Valida o cpf:
            ValidadorCPF pf = new ValidadorCPF(fmtxtcpf.getText());
            if (pf.isCPF()){
                lbcpf.setText("CPF:");
                lbcpf.setForeground(java.awt.Color.white);
            }
            else { 
                lbcpf.setText("CPF*:");
                lbcpf.setForeground(java.awt.Color.red);
                erro = 1;
                fmtxtcpf.setText(null);
            }
            
            //Verifica se o cpf já consta no bd:
            if(dao.RepeticaoCpf(fmtxtcpf.getText())){
                lbcpf.setText("CPF*:");
                lbcpf.setForeground(java.awt.Color.red);
                JOptionPane.showMessageDialog(null, "Este CPF já está cadastrado no banco de dados!", "Invalid CPF!", JOptionPane.ERROR_MESSAGE);
                erro = 1;
                fmtxtcpf.setText(null);
            }
            
            //valida o Nº de telefone
            LoginDAO fone = new LoginDAO();
            if (fone.isTelefone(fmtxtfone.getText())) {
                lbfone.setText("Telefone:");
                lbfone.setForeground(java.awt.Color.white);
            }
            else{
                lbfone.setText("Telefone*:");
                lbfone.setForeground(java.awt.Color.red);
                erro = 1;
            }
            
            //Verifica se o campo data está vazio:
            try{
                int test;
                test = Integer.parseInt(fmtxtnasc.getText().substring(9));
                
            }
            catch(Exception error){
                lbnasc.setText("Nascimento*:");
                lbnasc.setForeground(java.awt.Color.red);
                dterro=1;
                erro=1;
            }
            if(dterro==0){
            //Verifica se a data é válida:
            dia = fmtxtnasc.getText().substring(0,2);
            mes = fmtxtnasc.getText().substring(3, 5);
            ano = fmtxtnasc.getText().substring(6, 10);

            d = Integer.parseInt(dia);
            m = Integer.parseInt(mes);
            a = Integer.parseInt(ano);
            
            
            if((d<1 || d>31 || m<1 || m>12 || a<1910 || a>2019)){
                dterro = 1;
            }

            else if((m==4 || m==6 || m==9 || m==11) && d>30 ){
                dterro = 1;
            }

            else if(m==2){
                if((a%4==0 && a%100!=0 || a%400==0) && d>29 ){
                    dterro = 1;
                }
                else if(a%4!=0 && d>28){
                    dterro = 1;
                }
            }
            if(dterro==1){
                lbnasc.setText("Nascimento*:");
                lbnasc.setForeground(java.awt.Color.red);
                fmtxtnasc.setText(null);
                erro=1;
            }
            else{
                lbnasc.setText("Nascimento:");
                lbnasc.setForeground(java.awt.Color.white);
            }
            }
            
            //Guarda os dados em um obj Login:
            Login obj = new Login();
            obj.setUser(txtuser.getText());
            obj.setEmail(txtemail.getText());
            obj.setSenha(psswsenha.getText());
            obj.setNome(txtnome.getText());
            obj.setCpf(fmtxtcpf.getText());
            obj.setSexo(strgSexo);
            obj.setNasc(fmtxtnasc.getText());
            obj.setFone(fmtxtfone.getText());
            
            

            if(erro==0){
                dao.CriarUsuario(obj);
                JOptionPane.showMessageDialog(null, "Login criado com sucesso!");
                /*txtuser.setText(null);
                txtemail.setText(null);
                psswsenha.setText(null);
                psswconfsenha.setText(null);*/
            }
            else{
                JOptionPane.showMessageDialog(null, "Os dados não foram cadastrados!\n\nVerifique se há campos em branco"
                        + "\nou dados inválidos.\n\nOs campos a serem corrigidos \nsão indicados em vermelho."
                        ,"Database notification!", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException | HeadlessException error){
            JOptionPane.showMessageDialog(null, "Erro ao criar login! ","Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(TelaOpc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
         //Enter:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtemail.requestFocus();
        }
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
         //Enter:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            psswsenha.requestFocus();
        }
    }//GEN-LAST:event_txtemailKeyPressed

    private void psswsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psswsenhaKeyPressed
        //Enter:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            psswconfsenha.requestFocus();
        }
    }//GEN-LAST:event_psswsenhaKeyPressed

    private void psswconfsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psswconfsenhaKeyPressed
       
    }//GEN-LAST:event_psswconfsenhaKeyPressed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeKeyPressed

    private void fmtxtfoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmtxtfoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmtxtfoneActionPerformed

    private void cbsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsexoActionPerformed
        //Botão de seleção de sexo:
        if(cbsexo.getSelectedIndex()==0){
            strgSexo = "indefinido";
        }
        if(cbsexo.getSelectedItem().equals("Masculino")){
            strgSexo = "Masculino";
        }
        else if(cbsexo.getSelectedItem().equals("Feminino")){
            strgSexo = "Feminino";
        }
        else if(cbsexo.getSelectedItem().equals("Outro")){
            strgSexo = "Outro";
        }
    }//GEN-LAST:event_cbsexoActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        TelaLogin telalogin = new TelaLogin();
        telalogin.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        txtuser.setText(null);
        psswsenha.setText(null);
        psswconfsenha.setText(null);
        txtnome.setText(null);
        txtemail.setText(null);
        fmtxtcpf.setText(null);
        cbsexo.setSelectedIndex(0);
        fmtxtfone.setText(null);
        fmtxtnasc.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaOpc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JComboBox cbsexo;
    private javax.swing.JFormattedTextField fmtxtcpf;
    private javax.swing.JFormattedTextField fmtxtfone;
    private javax.swing.JFormattedTextField fmtxtnasc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbcnfsenha;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbfone;
    private javax.swing.JLabel lbnasc;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbpasswmnm;
    private javax.swing.JLabel lbsenha;
    private javax.swing.JLabel lbsexo;
    private javax.swing.JLabel lbuser;
    private javax.swing.JPasswordField psswconfsenha;
    private javax.swing.JPasswordField psswsenha;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
