/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MEIEIRO.telaCadastro;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author jarde
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        
        initComponents();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    int xx;
    int xy;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        lbBtn_Meieiros = new javax.swing.JLabel();
        lbBtn_Produtos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(87, 34));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_sidebar.setBackground(new java.awt.Color(34, 41, 50));
        pnl_sidebar.setForeground(new java.awt.Color(255, 255, 255));
        pnl_sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_sidebarMouseDragged(evt);
            }
        });
        pnl_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_sidebarMousePressed(evt);
            }
        });

        lbBtn_Meieiros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBtn_Meieiros.setForeground(new java.awt.Color(166, 166, 166));
        lbBtn_Meieiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-mais-25.png"))); // NOI18N
        lbBtn_Meieiros.setText("Meieiros");
        lbBtn_Meieiros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtn_MeieirosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbBtn_MeieirosMousePressed(evt);
            }
        });

        lbBtn_Produtos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBtn_Produtos.setForeground(new java.awt.Color(166, 166, 166));
        lbBtn_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-mais-25.png"))); // NOI18N
        lbBtn_Produtos.setText("Produtos");
        lbBtn_Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtn_ProdutosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbBtn_ProdutosMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconIFPA_1.png"))); // NOI18N

        lbl_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_5.setForeground(new java.awt.Color(166, 166, 166));
        lbl_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-finn-25.png"))); // NOI18N
        lbl_5.setText("Sobre");
        lbl_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_5MousePressed(evt);
            }
        });

        jButton1.setText("Leitor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(pnl_sidebarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbBtn_Produtos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbBtn_Meieiros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(lbBtn_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBtn_Meieiros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(34, 41, 50));

        jDesktopPane2.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane2.setToolTipText("Desenvolvido Por Jardel Castro");
        jDesktopPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDesktopPane2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane2)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnl_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jDesktopPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane2MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDesktopPane2MouseReleased

    private void lbBtn_ProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtn_ProdutosMousePressed
         setLblColor(lbBtn_Produtos);
         resetLblColor(lbBtn_Meieiros);
         resetLblColor(lbl_5);
    }//GEN-LAST:event_lbBtn_ProdutosMousePressed

    private void lbBtn_MeieirosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtn_MeieirosMousePressed
         setLblColor(lbBtn_Meieiros);
         resetLblColor(lbBtn_Produtos);
         resetLblColor(lbl_5);
    }//GEN-LAST:event_lbBtn_MeieirosMousePressed

    private void pnl_sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_sidebarMousePressed

    private void pnl_sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnl_sidebarMouseDragged

    private void lbBtn_ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtn_ProdutosMouseClicked
        try{
        TelaCadastroProdutos Telaprod = new TelaCadastroProdutos();
        jDesktopPane2.add(Telaprod);
        Telaprod.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha no Carregamento do Banco de Dados");
        }
    }//GEN-LAST:event_lbBtn_ProdutosMouseClicked

    private void lbBtn_MeieirosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtn_MeieirosMouseClicked
        // TODO add your handling code here:
        try{
        TelaCadastroMeieiros TelaCadMei = new TelaCadastroMeieiros();
        jDesktopPane2.add(TelaCadMei);
        TelaCadMei.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha no Carregamento do Banco de Dados");
        }
       
    }//GEN-LAST:event_lbBtn_MeieirosMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*JOptionPane.showMessageDialog(null, "Bem vindo ao Sistema de Cadastro de Usuários");
        JOptionPane.showMessageDialog(null, "A sua esquerda você pode escolher as opções\n"
        + "de cadastro do tipo aluno ou professor"
        + "e as \ntabelas de registros do tipo professor, aluno.");*/
    }//GEN-LAST:event_formWindowOpened

    private void lbl_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MouseClicked
        // TODO add your handling code here:
        //new Sobre().setVisible(true);
    }//GEN-LAST:event_lbl_5MouseClicked

    private void lbl_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MousePressed
        // TODO add your handling code here:
        setLblColor(lbl_5);
         resetLblColor(lbBtn_Produtos);
         resetLblColor(lbBtn_Meieiros);
    }//GEN-LAST:event_lbl_5MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //new clientes().setVisible(true);//que quer abrir
        new TelaLeitura().setVisible(true);
        //dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setLblColor(JLabel lbl) {
        lbl.setForeground(new Color(48, 201, 235));
    }

    public void resetLblColor(JLabel lbl) {
        lbl.setForeground(new Color(166, 166, 166));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBtn_Meieiros;
    private javax.swing.JLabel lbBtn_Produtos;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JPanel pnl_sidebar;
    // End of variables declaration//GEN-END:variables
}
